apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test0310goquayio 
  janus-idp.io/tekton: test0310goquayio
  backstage.io/kubernetes-id: test0310goquayio
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test0310goquayio
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml