apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test0310goquayio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test0310goquayio 
  name: test0310goquayio
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test0310goquayio 
